export const ENQUETE_BATCHES = [
  { number: 1, stage: 2, documents: [
    { id: 'registre-biometrique', title: 'Registre biométrique', file: '03_Registre_biometrique.pdf' },
    { id: 'ancres', title: 'Page sur les ancres', file: '16_Page_sur_les_ancres.pdf' },
    { id: 'lettre-lyna', title: 'Lettre à Lyna', file: '14_Lettre_a_Lyna.pdf' },
    { id: 'emargement', title: 'Émargement photo', file: '17_Emargement_photo.pdf' },
    { id: 'notice-historique', title: 'Notice historique', file: '07_Notice_historique.pdf' },
    { id: 'lettre-milo', title: 'Lettre de Milo', file: '15_Lettre_Milo.pdf' },
    { id: 'post-it', title: 'Post-it de Vasco', file: '08_Post_it_Vasco.pdf' },
    { id: 'journal-intime', title: 'Journal intime de Nora', file: '19_Journal_intime_Nora.pdf' },
  ] },
  { number: 2, stage: 3, documents: [
    { id: 'rapport-papillaire', title: 'Rapport papillaire', file: '04_Rapport_papillaire.pdf' },
    { id: 'photographies', title: 'Photographies automatiques', file: '05_Photographies_automatiques.pdf' },
    { id: 'arbre-genealogique', title: 'Arbre généalogique Remali', file: '06_Arbre_genealogique_Remali.pdf' },
    { id: 'messages-vasco', title: 'Messages de Vasco', file: '09_Messages_Vasco.pdf' },
    { id: 'ordre-mission', title: 'Ordre de mission Orsen', file: '10_Ordre_de_mission_Orsen.pdf' },
    { id: 'alibi-remali', title: 'Alibi de Remali', file: '11_Alibi_01_remali.pdf' },
    { id: 'alibi-kern', title: 'Alibi de Kern', file: '11_Alibi_02_kern.pdf' },
    { id: 'alibi-saran', title: 'Alibi de Saran', file: '11_Alibi_03_saran.pdf' },
    { id: 'alibi-bellini', title: 'Alibi de Bellini', file: '11_Alibi_04_bellini.pdf' },
    { id: 'alibi-orsen', title: 'Alibi d’Orsen', file: '11_Alibi_05_orsen.pdf' },
    { id: 'alibi-montfaucon', title: 'Alibi de Montfaucon', file: '11_Alibi_06_de_montfaucon.pdf' },
    { id: 'note-vigile', title: 'Note au vigile', file: '12_Note_au_vigile.pdf' },
    { id: 'inventaire', title: 'Inventaire d’Adrien', file: '13_Inventaire_Adrien.pdf' },
    { id: 'lettre-elise', title: 'Lettre à Élise', file: '14_Lettre_a_Elise.pdf' },
    { id: 'signalement', title: 'Signalement de disparition', file: '18_Signalement_disparition.pdf' },
    { id: 'carnet', title: 'Carnet d’enquête', file: '21_Carnet_enquete.pdf' },
  ] },
] as const;
